spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hellopig?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    hikari:
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      max-lifetime: 1765000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 15
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    open-in-view: false
